- implementations/DigitalBazaar.json
The previous instance had expired zcaps and so was giving a 500 unspecified error when issuing credentials.
This update has been tested with `vc-di-eddsa-2022-test-suite`.  DB issuance tests are passing with this update.
```
Tests passed 161/164 98%
Tests failed 3/164 2%
Failures 3
Tests skipped 0
Total tests 164
```
> Update DB `eddsa-2022` issuer.

- README.md
- implementations/ApiCatalog.json
- implementations/DigitalBazaar.json
- implementations/SpruceID.json
- implementations/Trinsic.json
- Add `supportedEcdsaKeyTypes` property to ` ecdsa-rdfc-2019` issuer and verifier implementations
- Update DB implementations.
Related PRs:
https://github.com/w3c/vc-di-eddsa-test-suite/pull/24
https://github.com/w3c/vc-di-ecdsa-test-suite/pull/19
> Update tag names for ecdsa and eddsa test suites.

- implementations/DigitalBazaar.json
Corrects a minor mistake in the DB manifest where the verifier for `ecdsa-sd-2023` was claming to support `P-256` and `P-384` when it only supports `P-256` currently.
> Separate DB verifier so that sd verifier only supports P-256.

- CHANGELOG.md
- README.md
- implementations/index.js
Adds 2 new features:
1. a new property `only` that can be attached to an implementation so only specific implementations run in a suite
2. support for non-dot file `localImplementationsConfig.cjs` files
3. Adds a CHANGELOG
This PR makes this PR possible: https://github.com/w3c/vc-di-ecdsa-test-suite/pull/47
Discussion:
1. Should we only allow / check local implementations for `only: true`?
> Only run local

- implementations/GrottoNetworking.json
- test/implementations.spec.js
One implementation was using an incorrect issuer ID DID:key.
This PR corrects the issue and adds a local test to ensure all issuers using DID:key ids are correct going forward.
> Fix incorrect issuer IDs for GrottoNetworking.

- CHANGELOG.md
- README.md
- implementations/index.js
- lib/main.js
This is an untested DRAFT PR, but it theoretically adds support for a `localConfig.cjs` file
> Add initial localConfig setup.

- implementations/index.js
So I believe this fixes the `localConfig.settings` to work the way intended.
What is mostly does is this: when using the javascript object spread syntax, the first object is overwritten by the next spread object. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax
```js
> const a = {foo: true}
> const b = {foo: false}
// b is last so it's values will take precedence
> const aB = {...a, ...b}
> aB
{ foo: false }
// a is last so it's values will take precedence
> const bA = {...b, ...a}
> bA
{ foo: true }
```
So basically this PR means that the value of `localConfig.settings` overwrites the first set of defaults.
This means that `settings.enableInteropTests` and `settings.testAllImplementations` from a test suite's localConfig will overwrite the …
> Overwrite default with localConfig.settings.

- implementations/DigitalBazaar.json
adds `supports.vc: ["1.1", "2.0"]` to the ecdsa endpoints expanding test coverage.
> Add supports.vc to ecdsa endpoints.

- implementations/DigitalBazaar.json
replaces id with a `did:key` and uses a VC 2.0 endpoint for the tests
Before replacement 95% conformance for DB after replacement 95% conformance for DB.
> Replace eddsa-rdfc-2022 endpoint with VC 2.0 version.

- README.md
1. Adds `bbs-2023` to README's tags section.
2. Cuts down on usage of `you` and `yours` in README improving the clarity of the README.
> Add bbs-2023 to README and improve tag description language.

- lib/main.js
localSettings is used in both ecdsa and bbs test suites.
It is also pretty useful and in the future might be used for more options.
> PATCH: Export localSettings.

- implementations/DigitalBazaar.json
@PatStLouis @BigBlueHat adds `options.checks = ['poof']` to the db verifier endpoint.
This is how we usually let implementers specify options that have been deprecated by the VC API, but 
they haven't had the time or resources to correct on their endpoints.
> Add checks to db verifier.

- implementations/GrottoNetworking.json
Added ecdsa-jcs-2019 and eddsa-jcs-2022 endpoints.
> Update GrottoNetworking.json for additional endpoints

- implementations/OpSecId.json
Current name takes up useless space in the reports because of column width. Replacing the full name with an alias for better user readability.
> Shorten Open Security and Identity implementation name

- README.md
This adds missing tag information in the readme.
> Add BitstringStatusList and eddsa-jcs-2022 tag information

- lib/requests.js
Small improvement, removes an overly SHOUTY string in favor of a more subtle one.
> Switch from shouty case to lowercase for header sanitization.

- implementations/Trential.json
`bitstring-status-list-test-suite` should run after https://github.com/w3c/vc-bitstring-status-list-test-suite/pull/49 fix is merged.
> Add trential implementation

- README.md
Improves the README by making implementers aware of test suite specific properties, endpoints, tags, and contexts.
> Expand README with warning about additional properties & contexts.

- test/implementations.spec.js
Some implementers only have verifiers. Now the tests in this repo knows that.
> Make issuers optional.

- implementations/ProcivisOneCore.json
Minor updates to the Procivis One Core configuration.
Partially a follow-up to [this earlier PR](https://github.com/w3c-ccg/vc-test-suite-implementations/pull/118). Removed the `vc-api` tags and the `didResolvers` config section. Also updated a previously incorrect issuer identifier / DID.
It seems like the used `tags` / `options` can be cleaned up / improved further, but if that's okay we'd rather do this in a follow-up PR after more local testing to ensure we don't introduce regressions.
Thank you!
> Update Procivis One Core configuration

- implementations/DigitalBazaar.json
Only one endpoint needs to be tagged.
> Remove vc2.0 tag from other DB endpoints.

- .github/workflows/compare-json.yaml
- implementations/DigitalBazaar.json
Due to the nature of testing GitHub Actions...this will need to be merged before we can really test drive it...but please let me know if you see anything glaringly wrong!
> Use jq to diff changes to implementation JSONs.
